name: textgram
description: "Mini tg-client."
publish_to: 'none'
version: 0.0.4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  ffi: 2.1.4
  provider: ^6.1.1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
     - family: JetBrains
       fonts:
         - asset: assets/fonts/JetBrainsMono-Regular.ttf
         - asset: assets/fonts/JetBrainsMono-Bold.ttf
           weight: 700
         - asset: assets/fonts/JetBrainsMono-Italic.ttf
           style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/icon.png"
  min_sdk_android: 21
